name: tla
root: /Users/neilpenning/vaults/deck_hone_loop/tlaplus

windows:
  - editor:
      layout: main-vertical
      panes:
        - nvim $(date +%Y-%m-%d).md
  - remote:
      layout: even-horizontal
      panes:
        - ssh deuterium -t "tmux"
  - hone:
      layout: even-horizontal
      panes:
        - isodate >> .hone
on_start:
  - tmux send-keys -t tla:0 'C-b B'
